#!/bin/sh
export ALTERNATE_EDITOR=""  # belt
if [ -z "$(ps aux | grep emacs | grep -v grep)" ]; then
    # start emacs server if not already running
    emacs --daemon && echo "started emacs server"
fi

tmux new-session -d -s 'lx' -n 'phd'
tmux send-keys 'emacsclient -nw' C-m
tmux split-window -v -p 10

tmux new-window -n 'teach'
tmux send-keys 'emacsclient -nw' C-m
tmux split-window -v -p 10

tmux attach -t 'lx'
